package com.freshfish.mathmaster.check;

import com.freshfish.mathmaster.init.ModBlocks;
import com.freshfish.mathmaster.tree.CollatzTreeGrowth;
import com.freshfish.mathmaster.tree.CollatzTreeSavedData;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.nbt.Tag;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.level.block.Blocks;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;

/** Runs real growth/world mutation with a controlled clock, outside player saves. */
public final class CollatzTreeGrowthCheck {
    private static int checks;
    private static final Set<BlockPos> touched = new HashSet<>();

    public static int run(ServerLevel level) {
        checks = 0;
        long originalTime = level.getGameTime();
        try {
            for (int initial = 5; initial <= 10; initial++) fullSequence(level, initial);
            blockedAndBroken(level);
            rooting(level);
            unloadedPause(level);
            branching(level);
            colorVariants(level);
        } finally {
            for (BlockPos pos : touched) CollatzTreeSavedData.get(level).removeAt(pos);
            for (BlockPos pos : touched) level.setBlockAndUpdate(pos, Blocks.AIR.defaultBlockState());
            touched.clear();
            ((net.minecraft.world.level.storage.ServerLevelData)level.getLevelData()).setGameTime(originalTime);
        }
        return checks;
    }

    private static void colorVariants(ServerLevel level) {
        for (var family : new com.freshfish.mathmaster.tree.CollatzTreeFamily[]{
                com.freshfish.mathmaster.tree.CollatzTreeFamily.PURPLE,
                com.freshfish.mathmaster.tree.CollatzTreeFamily.BLUE}) {
            BlockPos root = new BlockPos(7200 + family.ordinal()*96, 210, 320);
            level.getChunkAt(root); level.getChunkAt(root.offset(-16,0,-16)); level.getChunkAt(root.offset(16,0,16));
            level.setBlockAndUpdate(root, Blocks.DIRT.defaultBlockState());
            level.setBlockAndUpdate(root.above(), family.sapling().defaultBlockState());
            CollatzTreeGrowth.root(level,root.above());
            require(level.getBlockState(root).is(family.root()), "colored sapling roots in own family");
            require(level.getBlockState(root.above()).is(family.log()), "colored first log");
            var data = CollatzTreeSavedData.get(level);
            data.start(root,2,level.getGameTime());
            var snapshot=data.save(new CompoundTag(),level.registryAccess());
            var entries=snapshot.getList("trees",Tag.TAG_COMPOUND);
            for(int i=0;i<entries.size();i++) if(entries.getCompound(i).getLong("root")==root.asLong()) entries.getCompound(i).putInt("fork_budget",0);
            data=CollatzTreeSavedData.load(snapshot,level.registryAccess());
            level.getDataStorage().set("mathmaster_collatz_trees",data);
            require(data.isGrowing(root), "colored tree survives unchanged save format");
            for(int t=0;t<160 && data.isGrowing(root);t++) {
                ((net.minecraft.world.level.storage.ServerLevelData)level.getLevelData()).setGameTime(level.getGameTime()+1);
                data.tick(level);
            }
            require(!data.isGrowing(root), "colored sequence reaches terminal value one");
            int nodes=0, fruit=0;
            boolean wrongColor=false;
            for(BlockPos pos:BlockPos.betweenClosed(root.offset(-8,-8,-8),root.offset(8,8,8))) {
                var block=level.getBlockState(pos);
                if(block.is(family.node()))nodes++;
                if(block.is(family.leaves(true)))fruit++;
                if(block.is(family.root()) || block.is(family.log()) || block.is(family.node())
                        || block.is(family.leaves(false)) || block.is(family.leaves(true))) touched.add(pos.immutable());
                wrongColor |= block.is(ModBlocks.COLLATZ_LOG.get()) || block.is(ModBlocks.COLLATZ_NODE.get())
                        || block.is(ModBlocks.COLLATZ_LEAVES.get()) || block.is(ModBlocks.FRUITING_COLLATZ_LEAVES.get());
            }
            require(!wrongColor, "no red blocks generated by colored tree");
            require(nodes==2 && fruit>0, "own-color nodes and fruiting foliage");
            level.setBlockAndUpdate(root.above(),family.log().defaultBlockState());
            data.start(root,5,level.getGameTime());
            level.setBlockAndUpdate(root.above(),Blocks.AIR.defaultBlockState());
            require(!data.isGrowing(root), "colored log destruction permanently stops controller");
        }
    }

    private static CompoundTag state(CollatzTreeSavedData data, ServerLevel level, BlockPos root) {
        var list = data.save(new CompoundTag(), level.registryAccess()).getList("trees", Tag.TAG_COMPOUND);
        for (int i=0; i<list.size(); i++) if (list.getCompound(i).getLong("root")==root.asLong()) return list.getCompound(i);
        return null;
    }

    private static BlockPos seed(ServerLevel level, int initial, int x) {
        BlockPos root = new BlockPos(x, 150, 320);
        level.getChunkAt(root);
        level.setBlockAndUpdate(root, ModBlocks.COLLATZ_ROOT.get().defaultBlockState());
        level.setBlockAndUpdate(root.above(), ModBlocks.COLLATZ_LOG.get().defaultBlockState());
        touched.add(root); touched.add(root.above());
        CollatzTreeSavedData.get(level).start(root, initial, level.getGameTime());
        var data=CollatzTreeSavedData.get(level);
        var snapshot=data.save(new CompoundTag(),level.registryAccess());
        var entries=snapshot.getList("trees",Tag.TAG_COMPOUND);
        for(int i=0;i<entries.size();i++) if(entries.getCompound(i).getLong("root")==root.asLong()) entries.getCompound(i).putInt("fork_budget",0);
        level.getDataStorage().set("mathmaster_collatz_trees",CollatzTreeSavedData.load(snapshot,level.registryAccess()));
        return root;
    }

    private static void loadNeighbors(ServerLevel level, CompoundTag state) {
        BlockPos tip = BlockPos.of(state.getLong("tip"));
        level.getChunkAt(tip);
        for (Direction d: Direction.values()) level.getChunkAt(tip.relative(d));
    }

    private static void record(CompoundTag state) {
        if (state==null) return;
        for (long pos:state.getLongArray("wood")) {
            BlockPos p=BlockPos.of(pos); touched.add(p);
            for (Direction d:Direction.values()) touched.add(p.relative(d));
        }
    }

    private static void fullSequence(ServerLevel level, int initial) {
        var data=CollatzTreeSavedData.get(level);
        BlockPos root=seed(level,initial,400+initial*220);
        data=CollatzTreeSavedData.get(level);
        var expected=new ArrayList<Integer>();
        int sum=0;
        for (int n=initial;;n=n%2==0?n/2:3*n+1) { expected.add(n); sum+=n; if(n==1) break; }
        var actual=new ArrayList<Integer>();
        BlockPos lastNode=root;
        Set<BlockPos> wood=new HashSet<>();
        for (int tick=0; tick<12000 && data.isGrowing(root); tick++) {
            CompoundTag before=state(data,level,root); record(before); loadNeighbors(level,before);
            for(long p:before.getLongArray("wood")) wood.add(BlockPos.of(p));
            ((net.minecraft.world.level.storage.ServerLevelData)level.getLevelData()).setGameTime(level.getGameTime()+1);
            data.tick(level);
            CompoundTag after=state(data,level,root);
            if(after!=null) {
                record(after);
                BlockPos node=BlockPos.of(after.getLong("node"));
                if(!node.equals(lastNode)) {
                    actual.add(after.getInt("value"));lastNode=node;
                    long wait=after.getLong("next_tick")-level.getGameTime();
                    require(wait==40,"node waits exactly two seconds");
                }
            } else {
                actual.add(1);
                BlockPos tip=BlockPos.of(before.getLong("tip"));
                for(Direction d:Direction.values()) if(level.getBlockState(tip.relative(d)).is(ModBlocks.COLLATZ_NODE.get())) {
                    BlockPos node=tip.relative(d); wood.add(node); touched.add(node);
                    for(Direction side:Direction.values()) touched.add(node.relative(side));
                }
            }
        }
        require(!data.isGrowing(root),"initial "+initial+" finishes within bounded time");
        require(actual.equals(expected),"actual node sequence matches Collatz for "+initial);
        long logs=wood.stream().filter(p->level.getBlockState(p).is(ModBlocks.COLLATZ_LOG.get())).count();
        require(logs==sum,"actual log count equals sum of sequence lengths for "+initial);
        require(touched.stream().anyMatch(p->level.getBlockState(p).is(ModBlocks.FRUITING_COLLATZ_LEAVES.get())),"one produces fruiting foliage");
        // Remove this completed tree so later checks cannot mistake its foliage for a new result.
        for(BlockPos pos:new HashSet<>(touched)) level.setBlockAndUpdate(pos,Blocks.AIR.defaultBlockState());
        touched.clear();
    }

    private static void blockedAndBroken(ServerLevel level) {
        var data=CollatzTreeSavedData.get(level);
        BlockPos root=seed(level,6,2048), tip=root.above();
        data=CollatzTreeSavedData.get(level);
        var initial=state(data,level,root);loadNeighbors(level,initial);
        ((net.minecraft.world.level.storage.ServerLevelData)level.getLevelData()).setGameTime(initial.getLong("next_tick")-1);data.tick(level);
        require(state(data,level,root).getInt("total")==1,"no log before four ticks");
        for(Direction d:Direction.values()) if(d!=Direction.DOWN) {
            level.setBlockAndUpdate(tip.relative(d),Blocks.STONE.defaultBlockState());touched.add(tip.relative(d));
        }
        ((net.minecraft.world.level.storage.ServerLevelData)level.getLevelData()).setGameTime(level.getGameTime()+1);data.tick(level);
        require(data.isGrowing(root)&&state(data,level,root).getInt("total")==1,"all obstacles pause rather than cancel");
        level.setBlockAndUpdate(tip.east(),Blocks.AIR.defaultBlockState());
        ((net.minecraft.world.level.storage.ServerLevelData)level.getLevelData()).setGameTime(level.getGameTime()+4);data.tick(level);
        require(level.getBlockState(tip.east()).is(ModBlocks.COLLATZ_LOG.get()),"cleared obstacle resumes with a turn");
        record(state(data,level,root));
        var snapshot=data.save(new CompoundTag(),level.registryAccess());
        var restored=CollatzTreeSavedData.load(snapshot,level.registryAccess());
        require(restored.save(new CompoundTag(),level.registryAccess()).equals(snapshot),"all growth progress round-trips through NBT");
        level.setBlockAndUpdate(tip,Blocks.AIR.defaultBlockState());
        require(!data.isGrowing(root),"breaking a previous active log cancels immediately");
        level.setBlockAndUpdate(tip,ModBlocks.COLLATZ_LOG.get().defaultBlockState());
        ((net.minecraft.world.level.storage.ServerLevelData)level.getLevelData()).setGameTime(level.getGameTime()+100);data.tick(level);
        require(!data.isGrowing(root),"replacing log cannot restart a canceled tree");
        require(!CollatzTreeSavedData.load(data.save(new CompoundTag(),level.registryAccess()),level.registryAccess()).isGrowing(root),"cancellation survives save/load");

        BlockPos other=seed(level,5,2304);
        data=CollatzTreeSavedData.get(level);
        for(int i=0;i<100;i++) {
            var t=state(data,level,other);record(t);loadNeighbors(level,t);
            if(!BlockPos.of(t.getLong("node")).equals(other)) break;
            ((net.minecraft.world.level.storage.ServerLevelData)level.getLevelData()).setGameTime(level.getGameTime()+1);data.tick(level);
        }
        var node=BlockPos.of(state(data,level,other).getLong("node"));
        require(!node.equals(other),"first real node exists");
        level.setBlockAndUpdate(node,Blocks.AIR.defaultBlockState());
        require(!data.isGrowing(other),"breaking node during wait cancels immediately");
    }

    private static void rooting(ServerLevel level) {
        BlockPos sapling=new BlockPos(2560,150,320);level.getChunkAt(sapling);
        level.setBlockAndUpdate(sapling.below(),Blocks.DIRT.defaultBlockState());
        level.setBlockAndUpdate(sapling,ModBlocks.COLLATZ_SAPLING.get().defaultBlockState());
        touched.add(sapling);touched.add(sapling.below());
        CollatzTreeGrowth.root(level,sapling);
        require(level.getBlockState(sapling.below()).is(ModBlocks.COLLATZ_ROOT.get())
                &&level.getBlockState(sapling).is(ModBlocks.COLLATZ_LOG.get()),"supporting dirt becomes root, sapling becomes first log");
        var data=CollatzTreeSavedData.get(level);var t=state(data,level,sapling.below());
        require(t.getInt("value")>=5&&t.getInt("value")<=10&&t.getInt("remaining")==t.getInt("value")-1,"initial range and first log counted once");
        var before=data.save(new CompoundTag(),level.registryAccess());CollatzTreeGrowth.root(level,sapling);
        require(data.save(new CompoundTag(),level.registryAccess()).equals(before),"duplicate rooting cannot start twice");
        level.setBlockAndUpdate(sapling.below(),Blocks.AIR.defaultBlockState());
        require(!data.isGrowing(sapling.below()),"root destruction stops growth");
        level.setBlockAndUpdate(sapling.below(),Blocks.FARMLAND.defaultBlockState());
        level.setBlockAndUpdate(sapling,ModBlocks.COLLATZ_SAPLING.get().defaultBlockState());
        CollatzTreeGrowth.root(level,sapling);
        require(level.getBlockState(sapling.below()).is(ModBlocks.COLLATZ_ROOT.get()),"farmland also becomes root");
        data.removeAt(sapling.below());
    }

    private static void unloadedPause(ServerLevel level) {
        var data=CollatzTreeSavedData.get(level);
        BlockPos root=new BlockPos(100000,150,100000);
        require(!level.hasChunkAt(root),"pause test starts in an unloaded chunk");
        long now=level.getGameTime();
        data.start(root,6,now);touched.add(root);touched.add(root.above());
        data.tick(level);
        ((net.minecraft.world.level.storage.ServerLevelData)level.getLevelData()).setGameTime(now+100);
        data.tick(level);
        require(!level.hasChunkAt(root)&&state(data,level,root).getInt("total")==1,"unloaded growth never forces a chunk or advances");
        var paused=data.save(new CompoundTag(),level.registryAccess());
        require(CollatzTreeSavedData.load(paused,level.registryAccess()).save(new CompoundTag(),level.registryAccess()).equals(paused),"paused timer survives serialization");
        level.getChunkAt(root);
        level.setBlockAndUpdate(root,ModBlocks.COLLATZ_ROOT.get().defaultBlockState());
        level.setBlockAndUpdate(root.above(),ModBlocks.COLLATZ_LOG.get().defaultBlockState());
        data.tick(level);
        require(state(data,level,root).getLong("next_tick")==now+104&&state(data,level,root).getInt("total")==1,"loading preserves the remaining four ticks without catch-up");
        level.setBlockAndUpdate(root,Blocks.AIR.defaultBlockState());
    }

    private static void branching(ServerLevel level) {
        int[] counts=new int[3];
        for(int roll=0;roll<100;roll++) {
            counts[CollatzTreeGrowth.forkCount(roll,49)-1]++;
            require(CollatzTreeGrowth.forkCount(roll,0)==1,"exhausted budget always produces one");
            require(CollatzTreeGrowth.forkCount(roll,1)<=2,"last credit cannot produce three");
        }
        require(counts[0]==60&&counts[1]==30&&counts[2]==10,"exact 60/30/10 distribution");
        require(CollatzTreeGrowth.MAX_LOGS==16384&&CollatzTreeGrowth.MAX_ENDPOINTS==50,"new hard limits");
        // A real node with two remaining endpoint credits produces three distinct starts.
        BlockPos root=new BlockPos(2800,150,320), node=root.above();
        level.getChunkAt(root);
        level.setBlockAndUpdate(root,ModBlocks.COLLATZ_ROOT.get().defaultBlockState());
        level.setBlockAndUpdate(node,ModBlocks.COLLATZ_NODE.get().defaultBlockState());
        touched.add(root);touched.add(node);
        var data=CollatzTreeSavedData.get(level);data.start(root,2,level.getGameTime());
        var snapshot=data.save(new CompoundTag(),level.registryAccess());
        var entries=snapshot.getList("trees",Tag.TAG_COMPOUND);
        var tree=entries.getCompound(entries.size()-1);
        tree.putInt("fork_budget",2);tree.putInt("completed",47);
        var b=tree.getList("branches",Tag.TAG_COMPOUND).getCompound(0);
        b.putLong("node",node.asLong());b.putLong("tip",node.asLong());b.putInt("remaining",-1);
        b.putLongArray("segment",new long[0]);b.putLong("next_tick",level.getGameTime());
        // Also exercise the legacy single-branch reader with its original fields.
        var legacy=snapshot.copy();var old=legacy.getList("trees",Tag.TAG_COMPOUND).getCompound(entries.size()-1);
        old.merge(b);old.remove("branches");
        require(CollatzTreeSavedData.load(legacy,level.registryAccess()).isGrowing(root),"legacy single-tip progress migrates");
        level.getDataStorage().set("mathmaster_collatz_trees",CollatzTreeSavedData.load(snapshot,level.registryAccess()));
        data=CollatzTreeSavedData.get(level);
        long forcedSeed=0;
        while(net.minecraft.util.RandomSource.create(forcedSeed).nextInt(100)<90) forcedSeed++;
        level.random.setSeed(forcedSeed);
        data.tick(level);
        var after=state(data,level,root);record(after);
        var children=after.getList("branches",Tag.TAG_COMPOUND);
        require(children.size()==3&&after.getInt("fork_budget")==0,"three branches consume exactly two final credits");
        require(after.getInt("completed")==47,"completed endpoints never refund credits");
        Set<Long> tips=new HashSet<>();Set<Integer> directions=new HashSet<>();
        for(int i=0;i<children.size();i++) {
            var child=children.getCompound(i);tips.add(child.getLong("tip"));directions.add(child.getInt("direction"));
            require(child.getInt("value")==1&&child.getInt("remaining")==0,"each child uses next Collatz value and grows its own first log");
        }
        require(tips.size()==3&&directions.size()==3,"first logs grow in three distinct directions");
        require(CollatzTreeSavedData.load(data.save(new CompoundTag(),level.registryAccess()),level.registryAccess())
                .save(new CompoundTag(),level.registryAccess()).equals(data.save(new CompoundTag(),level.registryAccess())),"multi-branch clocks and budget round-trip");
        // Enclose one tip; the other two must still reach one independently.
        BlockPos blocked=BlockPos.of(children.getCompound(0).getLong("tip"));
        for(Direction d:Direction.values()) {
            BlockPos wall=blocked.relative(d);
            if(level.getBlockState(wall).isAir()) { level.setBlockAndUpdate(wall,Blocks.STONE.defaultBlockState());touched.add(wall); }
        }
        ((net.minecraft.world.level.storage.ServerLevelData)level.getLevelData()).setGameTime(level.getGameTime()+4);
        data.tick(level);after=state(data,level,root);record(after);
        require(after!=null&&after.getInt("completed")==49&&after.getList("branches",Tag.TAG_COMPOUND).size()==1,"blocked branch does not pause its siblings; total endpoint count stays fifty");
        require(after.getInt("fork_budget")==0,"completion never replenishes branching budget");
        level.setBlockAndUpdate(blocked.relative(Direction.UP),Blocks.AIR.defaultBlockState());
        ((net.minecraft.world.level.storage.ServerLevelData)level.getLevelData()).setGameTime(level.getGameTime()+4);
        data.tick(level);
        require(!data.isGrowing(root),"clearing last branch finishes the fiftieth endpoint");

        // Exactly one remaining log of the shared total is available, even with several tips.
        level.setBlockAndUpdate(node,ModBlocks.COLLATZ_LOG.get().defaultBlockState());
        data.start(root,6,level.getGameTime());snapshot=data.save(new CompoundTag(),level.registryAccess());
        tree=snapshot.getList("trees",Tag.TAG_COMPOUND).getCompound(0);tree.putInt("total",16383);
        level.getDataStorage().set("mathmaster_collatz_trees",CollatzTreeSavedData.load(snapshot,level.registryAccess()));
        data=CollatzTreeSavedData.get(level);
        ((net.minecraft.world.level.storage.ServerLevelData)level.getLevelData()).setGameTime(level.getGameTime()+4);
        data.tick(level);
        require(!data.isGrowing(root),"shared log limit permanently stops at 16384");
        touched.add(node.above());
    }

    private static void require(boolean success,String description) {
        if(!success) throw new AssertionError("Collatz growth: "+description);
        checks++;
    }
}
